/****** Object:  StoredProcedure [commercial].[SP_DM_PROCESS_SUGGEST]    Script Date: 5/9/2567 14:14:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [commercial].[SP_DM_PROCESS_SUGGEST] AS
BEGIN


DELETE
----SELECT COUNT(*) 
FROM [commercial].[DIGITAL_MAP_SUGGEST]
WHERE FIRST_DAY_OF_QUARTER IN (SELECT DISTINCT FIRST_DAY_OF_QUARTER FROM [commercial].[STG_DIGITAL_MAP_SUGGEST]);


INSERT INTO [commercial].[DIGITAL_MAP_SUGGEST]

SELECT 
[FIRST_DAY_OF_QUARTER],
[CUSTOMER_PARENT],
[Productid],
[CustomerName],
[FACING],
[ROW_NO],
[No_of_DS_Buy],
[DS_COUNT],
DATEADD(HH, 7, GETDATE()) AS UPDATE_DATE
--INTO [commercial].[DIGITAL_MAP_SUGGEST_TEMP]
FROM [commercial].[STG_DIGITAL_MAP_SUGGEST]

END
GO


