/****** Object:  View [commercial].[VW_DIGITAL_MAP_SUGGEST]    Script Date: 5/9/2567 14:15:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [commercial].[VW_DIGITAL_MAP_SUGGEST] AS WITH 
CD AS (
SELECT DISTINCT [YEAR], [MONTH], YEARMONTH AS YYYYMM, [YEAR]*100+[QUARTER] AS YYYYQQ, [QUARTER]
, LEFT([MONTHNAME], 3) AS MONTH_NAME 
, 'Q'+CONVERT(VARCHAR(1), FLOOR(([YEAR]*100+[QUARTER])%100))+''''+CONVERT(VARCHAR(2), FLOOR(YEAR%100)) AS QQYY
FROM [dbo].[DIM_Calendar]
WHERE DATE=CONVERT(DATE, DATEADD(HH, -7, GETDATE()-1), 112)   --(SELECT DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), -1))   --
)

SELECT
  /*SELECT convert(varchar(8), getdate(), 112), DATEPART(QQ, convert(DATE, '20211201', 112))*/
[FIRST_DAY_OF_QUARTER] 
, DATEPART(YY, [FIRST_DAY_OF_QUARTER]) AS [YEAR]
, DATEPART(QQ, [FIRST_DAY_OF_QUARTER]) AS [QUARTER]
, DATEPART(YY, [FIRST_DAY_OF_QUARTER])*100+DATEPART(QQ, [FIRST_DAY_OF_QUARTER]) AS YYYYQQ
, 'Q'+CONVERT(VARCHAR(1), DATEPART(QQ, [FIRST_DAY_OF_QUARTER]))
  +''''+CONVERT(VARCHAR(2), FLOOR(DATEPART(YY, [FIRST_DAY_OF_QUARTER]))%100) AS QQYY
, CONVERT(VARCHAR(3), DATENAME(MONTH, DATEADD(QUARTER, DATEDIFF(QUARTER, 0, [FIRST_DAY_OF_QUARTER]), 0)))
  +' - '+ CONVERT(VARCHAR(3), DATENAME(MONTH, DATEADD(QUARTER, DATEDIFF(QUARTER, 0, [FIRST_DAY_OF_QUARTER]) + 1, -1)))
  + ' '+ CONVERT(VARCHAR(4), DATEPART(YYYY, DATEADD(QUARTER, DATEDIFF(QUARTER, 0, [FIRST_DAY_OF_QUARTER]), 0))) AS QDESC

, [CUSTOMER_PARENT]
, [CustomerName]
, CONVERT(INT, DS.[Productid]) AS [Productid]
, [ProductShortName] AS [ProductDesc]
, [FACING]
, [ROW_NO]
, No_of_DS_Buy, DS_COUNT
, No_of_DS_Buy/CONVERT(DECIMAL(9,2), DS_COUNT) AS [PERCENTAGE]

--, DATEPART(MM, CONVERT(DATE, CONVERT(VARCHAR(6), [FIRST_DAY_OF_QUARTER])) - CD.MONTH AS CURRENT_MONTH_INDEX 
, DATEPART(QQ, [FIRST_DAY_OF_QUARTER]) - CD.[QUARTER] AS CURRENT_QUARTER_INDEX
, DATEPART(YY, [FIRST_DAY_OF_QUARTER]) - CD.YEAR AS CURRENT_YEAR_INDEX

--, CONVERT(DATE, CONVERT(VARCHAR(6), [FIRST_DAY_OF_QUARTER]) AS FIRST_DAY_OF_MONTH
, CONVERT(NVARCHAR(255), [CUSTOMER_PARENT]+'_'+CONVERT(VARCHAR(6), DATEPART(YY, [FIRST_DAY_OF_QUARTER])*100+DATEPART(QQ, [FIRST_DAY_OF_QUARTER]))) AS JOIN_KEY

FROM [commercial].[DIGITAL_MAP_SUGGEST] DS
LEFT JOIN [dbo].[DIM_ProductMaster] PD ON PD.[ProductId]=DS.[Productid]

CROSS JOIN CD;
GO


